/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Santé des dépendances (sans jeton) */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version de l'API et index actif */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste filtrée et triée des œuvres */
        get: operations["list_works_v1_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche d'une œuvre et de ses éditions */
        get: operations["get_work_v1_works__work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auteurs et traducteurs */
        get: operations["list_persons_v1_persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche d'une personne */
        get: operations["get_person_v1_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Arbre des courants littéraires */
        get: operations["list_movements_v1_movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/movements/{movement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Un courant et ses sous-courants */
        get: operations["get_movement_v1_movements__movement_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Langues du corpus */
        get: operations["list_languages_v1_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplétion : œuvres et personnes */
        get: operations["suggest_v1_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche détaillée d'une édition */
        get: operations["get_edition_v1_editions__edition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/toc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table des matières (arbre des sections) */
        get: operations["get_toc_v1_editions__edition_id__toc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Texte : plage de segments */
        get: operations["get_segments_v1_editions__edition_id__segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contenu d'une note */
        get: operations["get_note_v1_editions__edition_id__notes__note_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Où se trouve une position du texte */
        get: operations["get_position_v1_editions__edition_id__position_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recherche dans le livre (mots exacts) */
        get: operations["find_in_edition_v1_editions__edition_id__find_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/epub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fichier EPUB brut (GET ou HEAD) */
        get: operations["get_epub_v1_editions__edition_id__epub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/anchors:resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recaler des positions enregistrées sur une ancienne révision */
        post: operations["resolve_anchors_v1_editions__edition_id__anchors_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recherche : thème, citation ou mots */
        post: operations["search_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passages proches par le sens d'un passage donné */
        post: operations["similar_v1_similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works/{work_id}/alignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Qualité de l'alignement par édition */
        get: operations["work_alignment_v1_works__work_id__alignment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/counterpart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position correspondante dans une autre édition de l'œuvre */
        get: operations["counterpart_v1_editions__edition_id__counterpart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions/{edition_id}/parallel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lecture côte à côte */
        get: operations["parallel_v1_editions__edition_id__parallel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alignment/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Un lien tiré au hasard, à vérifier */
        get: operations["sample_v1_alignment_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alignment/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verdict sur un lien d'alignement */
        post: operations["create_review_v1_alignment_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alignment/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poser un lien manuel (correction) */
        post: operations["create_link_v1_alignment_links_post"];
        /** Supprimer un lien jugé faux */
        delete: operations["delete_link_v1_alignment_links_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changements du corpus depuis un curseur */
        get: operations["list_changes_v1_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlignmentLink */
        AlignmentLink: {
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
            /** Method */
            method: string;
            /** Score */
            score: number | null;
            source: components["schemas"]["LinkSide"];
            /**
             * Reference
             * @description Segments de l'édition de référence rattachés à la même unité.
             */
            reference: components["schemas"]["LinkSide"][];
        };
        /** AlignmentSummary */
        AlignmentSummary: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "reliable" | "doubtful" | "rejected";
            /** Aligned Ratio */
            aligned_ratio: number | null;
        };
        /** Anchor */
        Anchor: {
            /**
             * Key
             * @description Identifiant libre, renvoyé tel quel.
             */
            key: string;
            /** Revision */
            revision: number;
            /** Seq */
            seq: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            quote?: components["schemas"]["Quote"] | null;
        };
        /** AnchorResult */
        AnchorResult: {
            /** Key */
            key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "unchanged" | "relocated" | "approximate" | "lost";
            /** Seq */
            seq: number | null;
            /** Offset */
            offset: number | null;
        };
        /** AnchorsRequest */
        AnchorsRequest: {
            /** Anchors */
            anchors: components["schemas"]["Anchor"][];
        };
        /** AnchorsResponse */
        AnchorsResponse: {
            /** Revision */
            revision: number;
            /** Results */
            results: components["schemas"]["AnchorResult"][];
        };
        /** Author */
        Author: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Birth Year */
            birth_year?: number | null;
            /** Death Year */
            death_year?: number | null;
        };
        /** Change */
        Change: {
            /** Cursor */
            cursor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Type */
            type: string;
            /** Work Id */
            work_id: string | null;
            /** Edition Id */
            edition_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Changes */
        Changes: {
            /** Items */
            items: components["schemas"]["Change"][];
            /**
             * Next Cursor
             * @description Dernier curseur lu (à repasser en `after`), inchangé si vide.
             */
            next_cursor: string | null;
        };
        /** Contributor */
        Contributor: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "translator" | "editor" | "preface" | "illustrator";
        };
        /** Counterpart */
        Counterpart: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Language */
            language: string;
            /** Revision */
            revision: number;
            /** Seq Start */
            seq_start: number;
            /** Seq End */
            seq_end: number;
            /**
             * Via
             * @enum {string}
             */
            via: "segment" | "section";
            /** Score */
            score: number | null;
        };
        /** EditionAlignment */
        EditionAlignment: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Is Original */
            is_original: boolean;
            /** Is Reference */
            is_reference: boolean;
            /** Status */
            status: ("pending" | "reliable" | "doubtful" | "rejected") | null;
            /** Method */
            method: string | null;
            /** N Segments */
            n_segments: number | null;
            /** Aligned Ratio */
            aligned_ratio: number | null;
            /** Mean Score */
            mean_score: number | null;
            /** Low Score Ratio */
            low_score_ratio: number | null;
            /** Aligned At */
            aligned_at: string | null;
        };
        /** EditionDetail */
        EditionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Is Original */
            is_original: boolean;
            /** Translators */
            translators: components["schemas"]["PersonRef"][];
            /** Publisher */
            publisher: string | null;
            /** Year */
            year: number | null;
            /**
             * Access
             * @enum {string}
             */
            access: "open" | "excerpt" | "restricted";
            /** Revision */
            revision: number;
            alignment: components["schemas"]["AlignmentSummary"] | null;
            work: components["schemas"]["WorkRef"];
            /** Contributors */
            contributors: components["schemas"]["Contributor"][];
            /** N Pages */
            n_pages: number | null;
            /** N Segments */
            n_segments: number;
            /** Char Length */
            char_length: number;
            /** Has Page Breaks */
            has_page_breaks: boolean;
            /**
             * Reference Edition Id
             * @description Édition de référence de l'alignement (null = elle-même ou non alignée).
             */
            reference_edition_id: string | null;
            /** Epub Available */
            epub_available: boolean;
        };
        /** EditionRev */
        EditionRev: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Revision */
            revision: number;
        };
        /** EditionSummary */
        EditionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Is Original */
            is_original: boolean;
            /** Translators */
            translators: components["schemas"]["PersonRef"][];
            /** Publisher */
            publisher: string | null;
            /** Year */
            year: number | null;
            /**
             * Access
             * @enum {string}
             */
            access: "open" | "excerpt" | "restricted";
            /** Revision */
            revision: number;
            alignment: components["schemas"]["AlignmentSummary"] | null;
        };
        /** FindHit */
        FindHit: {
            /** Seq */
            seq: number;
            /** Offset */
            offset: number;
            /** Length */
            length: number;
            /** Snippet */
            snippet: string;
            /**
             * Snippet Offset
             * @description Position de la correspondance dans `snippet`.
             */
            snippet_offset: number;
            /** Section Path */
            section_path: string[];
        };
        /** FindResult */
        FindResult: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Revision */
            revision: number;
            /** Hits */
            hits: components["schemas"]["FindHit"][];
            /**
             * Truncated
             * @description Vrai si d'autres correspondances existent au-delà de `limit`.
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HitEdition */
        HitEdition: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Is Original */
            is_original: boolean;
            /**
             * Access
             * @enum {string}
             */
            access: "open" | "excerpt" | "restricted";
            /** Revision */
            revision: number;
        };
        /** HitWork */
        HitWork: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: components["schemas"]["PersonRef"][];
            /** First Published Year */
            first_published_year: number | null;
        };
        /** IndexInfo */
        IndexInfo: {
            /** Collection */
            collection: string;
            /** Dense Model */
            dense_model: string;
            /** Chunker Version */
            chunker_version: string;
        };
        /** LanguageCount */
        LanguageCount: {
            /** Language */
            language: string;
            /** N Editions */
            n_editions: number;
            /** N Works */
            n_works: number;
            /** N Originals */
            n_originals: number;
        };
        /** LinkRequest */
        LinkRequest: {
            source: components["schemas"]["ReviewSource"];
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
        };
        /** LinkSide */
        LinkSide: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Revision */
            revision: number;
            /** Seq */
            seq: number;
            /** Text */
            text: string;
        };
        /** Meta */
        Meta: {
            /** Api Version */
            api_version: string;
            /** Index */
            index: {
                [key: string]: unknown;
            } | null;
        };
        /** MovementDetail */
        MovementDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Start Year */
            start_year: number | null;
            /** End Year */
            end_year: number | null;
            /**
             * N Works
             * @description Œuvres du courant et de ses sous-courants.
             */
            n_works: number;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["MovementNode"][];
            /** Wikidata Id */
            wikidata_id: string | null;
            parent: components["schemas"]["MovementRef"] | null;
        };
        /** MovementNode */
        MovementNode: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Start Year */
            start_year: number | null;
            /** End Year */
            end_year: number | null;
            /**
             * N Works
             * @description Œuvres du courant et de ses sous-courants.
             */
            n_works: number;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["MovementNode"][];
        };
        /** MovementRef */
        MovementRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
        };
        /** Note */
        Note: {
            /**
             * Note Id
             * Format: uuid
             */
            note_id: string;
            /** Label */
            label: string | null;
            /** Origin */
            origin: string | null;
            /** Segments */
            segments: components["schemas"]["Segment"][];
        };
        /** NoteRef */
        NoteRef: {
            /**
             * Offset
             * @description Position de l'appel dans `text` du segment.
             */
            offset: number;
            /** Label */
            label: string;
            /**
             * Note Id
             * Format: uuid
             */
            note_id: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "author" | "translator" | "editor" | "unknown";
        };
        /** PageMark */
        PageMark: {
            /**
             * Offset
             * @description Début de la page dans `text` du segment.
             */
            offset: number;
            /** Label */
            label: string;
        };
        /** Page[PersonSummary] */
        Page_PersonSummary_: {
            /** Items */
            items: components["schemas"]["PersonSummary"][];
            /**
             * Next Cursor
             * @description À passer en `cursor` pour la page suivante ; null = fin.
             */
            next_cursor?: string | null;
        };
        /** Page[WorkSummary] */
        Page_WorkSummary_: {
            /** Items */
            items: components["schemas"]["WorkSummary"][];
            /**
             * Next Cursor
             * @description À passer en `cursor` pour la page suivante ; null = fin.
             */
            next_cursor?: string | null;
        };
        /** Parallel */
        Parallel: {
            source: components["schemas"]["EditionRev"];
            target: components["schemas"]["EditionRev"];
            /** Quality */
            quality: ("pending" | "reliable" | "doubtful" | "rejected") | null;
            /** Pairs */
            pairs: components["schemas"]["ParallelPair"][];
        };
        /** ParallelPair */
        ParallelPair: {
            /** Source Seqs */
            source_seqs: number[];
            /** Target Seqs */
            target_seqs: number[];
            /** Score */
            score: number | null;
            /** Method */
            method: string | null;
        };
        /** Passage */
        Passage: {
            /** Seq Start */
            seq_start: number;
            /** Seq End */
            seq_end: number;
            /** Section Path */
            section_path: string[];
            /** Page Label */
            page_label: string | null;
            /** Text */
            text: string;
            /**
             * Truncated
             * @description Extrait tronqué (édition `excerpt`).
             * @default false
             */
            truncated: boolean;
            /**
             * Highlights
             * @description Plages [début, fin[ dans `text`.
             * @default []
             */
            highlights: [
                number,
                number
            ][];
        };
        /** PersonDetail */
        PersonDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Sort Name */
            sort_name: string | null;
            /** Birth Year */
            birth_year: number | null;
            /** Death Year */
            death_year: number | null;
            /** Wikidata Id */
            wikidata_id: string | null;
            /**
             * N Works
             * @description Œuvres écrites (visibles).
             */
            n_works: number;
            /**
             * N Translations
             * @description Éditions traduites (visibles).
             */
            n_translations: number;
            /** Names */
            names: components["schemas"]["PersonName"][];
            /** Works */
            works: components["schemas"]["WorkRef"][];
            /** Translations */
            translations: components["schemas"]["Translation"][];
        };
        /** PersonName */
        PersonName: {
            /** Language */
            language: string;
            /** Name */
            name: string;
        };
        /** PersonRef */
        PersonRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** PersonSummary */
        PersonSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Sort Name */
            sort_name: string | null;
            /** Birth Year */
            birth_year: number | null;
            /** Death Year */
            death_year: number | null;
            /** Wikidata Id */
            wikidata_id: string | null;
            /**
             * N Works
             * @description Œuvres écrites (visibles).
             */
            n_works: number;
            /**
             * N Translations
             * @description Éditions traduites (visibles).
             */
            n_translations: number;
        };
        /** Position */
        Position: {
            /** Seq */
            seq: number;
            /** Offset */
            offset: number;
            /** Section Id */
            section_id: string | null;
            /** Path */
            path: string[];
            /** Page Label */
            page_label: string | null;
            /**
             * Progress
             * @description Part du texte avant cette position (0 à 1).
             */
            progress: number;
        };
        /** Quote */
        Quote: {
            /** Exact */
            exact: string;
            /**
             * Prefix
             * @default
             */
            prefix: string;
            /**
             * Suffix
             * @default
             */
            suffix: string;
        };
        /** ReviewCreated */
        ReviewCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            source: components["schemas"]["ReviewSource"];
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "correct" | "incorrect" | "partial";
            /**
             * Is Sample
             * @default false
             */
            is_sample: boolean;
            /** Comment */
            comment?: string | null;
        };
        /** ReviewSource */
        ReviewSource: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Seq */
            seq: number;
        };
        /** SearchFilters */
        SearchFilters: {
            /**
             * Languages
             * @default []
             */
            languages: string[];
            /**
             * Original Only
             * @default false
             */
            original_only: boolean;
            year?: components["schemas"]["YearRange"] | null;
            /**
             * Author Ids
             * @default []
             */
            author_ids: string[];
            /**
             * Movement Ids
             * @default []
             */
            movement_ids: string[];
            /**
             * Work Ids
             * @default []
             */
            work_ids: string[];
            /**
             * Edition Ids
             * @default []
             */
            edition_ids: string[];
        };
        /** SearchHit */
        SearchHit: {
            /** Score */
            score: number;
            /**
             * Exact
             * @description La citation figure mot pour mot dans le passage.
             * @default false
             */
            exact: boolean;
            work: components["schemas"]["HitWork"];
            edition: components["schemas"]["HitEdition"];
            passage: components["schemas"]["Passage"];
            /**
             * Translations
             * @default {}
             */
            translations: {
                [key: string]: components["schemas"]["TranslatedPassage"] | null;
            };
        };
        /** SearchRequest */
        SearchRequest: {
            /** Q */
            q: string;
            /**
             * Mode
             * @default theme
             * @enum {string}
             */
            mode: "theme" | "quote" | "words";
            /**
             * @default {
             *       "languages": [],
             *       "original_only": false,
             *       "author_ids": [],
             *       "movement_ids": [],
             *       "work_ids": [],
             *       "edition_ids": []
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /**
             * Group By
             * @default work
             * @enum {string}
             */
            group_by: "work" | "edition" | "none";
            /**
             * Show Languages
             * @default []
             */
            show_languages: string[];
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** SearchResponse */
        SearchResponse: {
            index: components["schemas"]["IndexInfo"];
            /** Took Ms */
            took_ms: number;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** Segment */
        Segment: {
            /** Seq */
            seq: number;
            /** Section Id */
            section_id: string | null;
            /** Kind */
            kind: string;
            /** Speaker */
            speaker: string | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Text */
            text: string;
            /** Markup */
            markup: string | null;
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["NoteRef"][];
            /**
             * Pages
             * @default []
             */
            pages: components["schemas"]["PageMark"][];
        };
        /** SegmentRange */
        SegmentRange: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Revision */
            revision: number;
            /** Total Segments */
            total_segments: number;
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Next From Seq */
            next_from_seq: number | null;
            /**
             * Notes
             * @description Contenu des notes appelées (include=notes).
             */
            notes?: {
                [key: string]: components["schemas"]["Note"];
            } | null;
        };
        /** SimilarRequest */
        SimilarRequest: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Seq Start */
            seq_start: number;
            /** Seq End */
            seq_end: number;
            /**
             * @default {
             *       "languages": [],
             *       "original_only": false,
             *       "author_ids": [],
             *       "movement_ids": [],
             *       "work_ids": [],
             *       "edition_ids": []
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /**
             * Group By
             * @default work
             * @enum {string}
             */
            group_by: "work" | "edition" | "none";
            /**
             * Exclude Same Work
             * @default true
             */
            exclude_same_work: boolean;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** Suggestion */
        Suggestion: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "work" | "person";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /**
             * Detail
             * @description Auteurs (œuvre) ou dates (personne).
             */
            detail?: string | null;
            /** Score */
            score: number;
        };
        /** Toc */
        Toc: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Revision */
            revision: number;
            /** Sections */
            sections: components["schemas"]["TocSection"][];
        };
        /** TocSection */
        TocSection: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Matter
             * @enum {string}
             */
            matter: "front" | "body" | "back";
            /** Label */
            label: string | null;
            /** Title */
            title: string | null;
            /** Number */
            number: number | null;
            /** Seq Start */
            seq_start: number | null;
            /** Seq End */
            seq_end: number | null;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["TocSection"][];
        };
        /** TranslatedPassage */
        TranslatedPassage: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Language */
            language: string;
            /** Seq Start */
            seq_start: number;
            /** Seq End */
            seq_end: number;
            /** Text */
            text: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** Translation */
        Translation: {
            /**
             * Edition Id
             * Format: uuid
             */
            edition_id: string;
            /** Edition Title */
            edition_title: string;
            /** Language */
            language: string;
            work: components["schemas"]["WorkRef"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkAlignment */
        WorkAlignment: {
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
            /** Reference Edition Id */
            reference_edition_id: string | null;
            /** N Units */
            n_units: number;
            /** Editions */
            editions: components["schemas"]["EditionAlignment"][];
        };
        /** WorkDetail */
        WorkDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string | null;
            /**
             * Title
             * @description Titre dans la langue d'affichage (repli : titre de référence).
             */
            title: string;
            /** Title Language */
            title_language: string | null;
            /** Original Title */
            original_title: string;
            /** Original Language */
            original_language: string | null;
            /** First Published Year */
            first_published_year: number | null;
            /** Authors */
            authors: components["schemas"]["Author"][];
            /** Movements */
            movements: components["schemas"]["MovementRef"][];
            /**
             * Languages
             * @description Langues des éditions visibles.
             */
            languages: string[];
            /** Wikidata Id */
            wikidata_id: string | null;
            /**
             * Titles
             * @description Titres connus, par langue.
             */
            titles: {
                [key: string]: string;
            };
            /** Editions */
            editions: components["schemas"]["EditionSummary"][];
        };
        /** WorkRef */
        WorkRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** First Published Year */
            first_published_year?: number | null;
        };
        /** WorkSummary */
        WorkSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string | null;
            /**
             * Title
             * @description Titre dans la langue d'affichage (repli : titre de référence).
             */
            title: string;
            /** Title Language */
            title_language: string | null;
            /** Original Title */
            original_title: string;
            /** Original Language */
            original_language: string | null;
            /** First Published Year */
            first_published_year: number | null;
            /** Authors */
            authors: components["schemas"]["Author"][];
            /** Movements */
            movements: components["schemas"]["MovementRef"][];
            /**
             * Languages
             * @description Langues des éditions visibles.
             */
            languages: string[];
        };
        /** YearRange */
        YearRange: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_works_v1_works_get: {
        parameters: {
            query?: {
                /** @description Titre, dans toutes les langues. */
                q?: string | null;
                author_id?: string | null;
                /** @description Courant, sous-courants compris. */
                movement_id?: string | null;
                /** @description Au moins une édition dans cette langue. */
                language?: string | null;
                original_language?: string | null;
                year_min?: number | null;
                year_max?: number | null;
                slug?: string | null;
                sort?: "title" | "-title" | "year" | "-year" | "author";
                /** @description Curseur de la page suivante (`next_cursor`). */
                cursor?: string | null;
                /** @description Nombre d'éléments (max 100). */
                limit?: number;
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_v1_works__work_id__get: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_v1_persons_get: {
        parameters: {
            query?: {
                role?: ("author" | "translator") | null;
                /** @description Nom, toutes graphies. */
                q?: string | null;
                /** @description Curseur de la page suivante (`next_cursor`). */
                cursor?: string | null;
                /** @description Nombre d'éléments (max 100). */
                limit?: number;
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PersonSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_v1_persons__person_id__get: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movements_v1_movements_get: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_movement_v1_movements__movement_id__get: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path: {
                movement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_languages_v1_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageCount"][];
                };
            };
        };
    };
    suggest_v1_suggest_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edition_v1_editions__edition_id__get: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_toc_v1_editions__edition_id__toc_get: {
        parameters: {
            query?: {
                /** @description Parties gardées (défaut : toutes). */
                matter?: ("front" | "body" | "back")[] | null;
                /** @description Inclure chaque note comme une section. */
                include_notes?: boolean;
                /** @description Révision attendue : réponse immuable (cache long) ; 409 si l'édition a changé. */
                rev?: number | null;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Toc"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segments_v1_editions__edition_id__segments_get: {
        parameters: {
            query?: {
                from_seq?: number;
                /** @description Dernier segment voulu (inclus). */
                to_seq?: number | null;
                limit?: number;
                /** @description notes : contenu des notes appelées. */
                include?: "notes"[] | null;
                /** @description Révision attendue : réponse immuable (cache long) ; 409 si l'édition a changé. */
                rev?: number | null;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRange"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_v1_editions__edition_id__notes__note_id__get: {
        parameters: {
            query?: {
                /** @description Révision attendue : réponse immuable (cache long) ; 409 si l'édition a changé. */
                rev?: number | null;
            };
            header?: never;
            path: {
                edition_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_v1_editions__edition_id__position_get: {
        parameters: {
            query: {
                seq: number;
                offset?: number;
                /** @description Révision attendue : réponse immuable (cache long) ; 409 si l'édition a changé. */
                rev?: number | null;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_in_edition_v1_editions__edition_id__find_get: {
        parameters: {
            query: {
                /** @description Casse et accents ignorés. */
                q: string;
                limit?: number;
                /** @description Révision attendue : réponse immuable (cache long) ; 409 si l'édition a changé. */
                rev?: number | null;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_epub_v1_editions__edition_id__epub_get: {
        parameters: {
            query?: {
                /** @description Content-Disposition: inline. */
                inline?: boolean;
                /** @description Révision attendue : réponse immuable (cache long) ; 409 si l'édition a changé. */
                rev?: number | null;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/epub+zip": unknown;
                };
            };
            /** @description Plage d'octets */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_anchors_v1_editions__edition_id__anchors_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnchorsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_post: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_v1_similar_post: {
        parameters: {
            query?: {
                /** @description Langue d'affichage (BCP 47), sinon Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    work_alignment_v1_works__work_id__alignment_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkAlignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    counterpart_v1_editions__edition_id__counterpart_get: {
        parameters: {
            query: {
                seq: number;
                /** @description Édition cible. */
                target?: string | null;
                /** @description Ou : langue cible (meilleure édition). */
                lang?: string | null;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Counterpart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parallel_v1_editions__edition_id__parallel_get: {
        parameters: {
            query: {
                target: string;
                from_seq: number;
                to_seq: number;
            };
            header?: never;
            path: {
                edition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Parallel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_v1_alignment_sample_get: {
        parameters: {
            query?: {
                method?: string | null;
                min_score?: number | null;
                max_score?: number | null;
                work_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlignmentLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_v1_alignment_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_link_v1_alignment_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_v1_alignment_links_delete: {
        parameters: {
            query: {
                edition_id: string;
                seq: number;
                unit_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_changes_v1_changes_get: {
        parameters: {
            query?: {
                /** @description Dernier curseur lu ; vide = depuis le début. */
                after?: string | null;
                limit?: number;
                /** @description Types gardés ; « edition. » = tous les types qui commencent ainsi. */
                type?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
